- 3ds/mbedtls/PKGBUILD
Release notes: https://tls.mbed.org/tech-updates/releases/mbedtls-2.8.0-2.7.2-and-2.1.11-released
> 3ds/mbedtls: Update to 2.8.0

- 3ds/libvorbis/PKGBUILD
I don't think the 3ds-libvorbis needs the switch-libogg, but rather 3ds-libogg.
Also set pkgrel one higher since there was a package info change.
> Fix 3ds-libvorbis dependency

- 3ds/libopus/PKGBUILD
This adds libopus for the 3ds. No idea why this wasn't made before (it was available when dkp used portlibs and was made avliable for the switch).
Please let me know if anything needs to be changed or fixed.
> Add libopus

- 3ds/opusfile/PKGBUILD
Requires libopus. Also was apart of dkp-portlibs but was never carried over.
> Add opusfile

- switch/libmikmod/PKGBUILD
- switch/libmikmod/libmikmod-switch-support.patch
This is an updated Switch driver for libmikmod. Improvements include:
- Double buffer output
- Updating the driver no longer blocks until the current buffer completes playing
- Fix mismatch of sample rates causing high pitch
An example usage can be viewed at [libjared/switch-music](https://github.com/libjared/switch-music).
> Update switch libmikmod driver

- ppc/libmad/PKGBUILD
- ppc/libmad/frame_length.patch
- ppc/libmad/optimise.diff
- ppc/libmad/pkg-config.patch
PKGBUILD for libmad, from #57.
I don't really know much about libogc's use of libmad. It seems to me that it does basically the same thing we're doing here, just placing the libraries in `libogc/lib/{wii,cube}` rather than portlibs. With any luck, the linker should be able to sort itself out and pick one or the other (likely whatever ends up first on the search path). If libogc has wii-specific modifications or optimisations then something more complex may have to be done.
Thanks,
Ash
> ppc: Add libmad

- switch/ode/PKGBUILD
- switch/ode/threading.patch
By default is build statically, with single precision, with ODE and libccd and without any thread support, should be enough for most homebrew.
Tested locally but with some custom hacks.
> Add libode to the switch ports

- switch/libvpx/PKGBUILD
- switch/libvpx/libvpx.patch
The symbol change from `sync` to `_sync` was due to a conflicting symbol in `unistd.h`.
> switch-libvpx: add package

- switch/ffmpeg/PKGBUILD
Depends on #93 
Enables VP8/VP9 and Opus codec used in videos from YouTube
> switch-ffmpeg: build with libopus and libvpx

- ppc/jansson/.gitignore
- ppc/jansson/PKGBUILD
The _PKGBUILD_ file is based on the 3DS version but this one uses ppc and libjansson version 2.12. libjansson v2.11 is also used for the Switch.
I have kept 3 commits because I think it might be easier to review the changes this way. If accepted I propose to Squash all commits into one before merging.
> Add libjansson to ppc

- switch/libsodium/PKGBUILD
Will be needed by future versions of Diablo.
> switch-libsodium 1.0.18

- switch/libgd/PKGBUILD
- switch/libgd/libgd-2.2.5-nosyslog.patch
Someone needed a library to resize images on the Switch. Saw libGD was available for PPC made a few simple modifications for it to compile for the Switch.
> Add switch-libgd

- switch/wslay/PKGBUILD
Godot websocket support uses wslay - this was tested with Godot's `websocket_multiplayer` demo and that appears to work.
> switch: add wslay

- switch/mbedtls/PKGBUILD
NOTE: I didn't confirm this actually work, but it probably does. At least the build was successful.
> Update switch-mbedtls to 2.16.6.

- switch/curl/PKGBUILD
- switch/curl/switch-curl.patch
This replaces the mbedtls tls backend with the newly implemented libnx tls backend. Also adds support for using the system proxy from nifmGetCurrentNetworkProfile.
This uses functionality currently only in libnx-git, so this is blocking on the next libnx stable release.
> switch-curl: libnx tls backend and system proxy support.

- switch/ffmpeg/PKGBUILD
`switch-libopus`, `switch-libtheora`, and `switch-libvpx` can be removed, as `ffmpeg` has builtin decoders for these formats.
The builtin codecs are more optimized than `libopus`, `libtheora`, and `libvpx`.
> switch-ffmpeg: update dependencies to remove switch-libopus, switch-libtheora, switch-libvpx

- pkgbuild-scripts/PKGBUILD
Not sure if this is the right way to submit this change 😂  I'm trying to make SDL for Wii install using the official build tools in case we can make it a pacman package (https://github.com/dborth/sdl-wii/issues/54) and noticed that vars file was missing.
Also I haven't changed the package version or `rel` number, happy to change those too if needed 😄 
EDIT: I just added `wiiuvars.sh` as requested 👍
> pkgbuild-scripts: Add wiivars.sh and wiiuvars.sh to the list of devkitPPC files to install

- switch/pkg-config/pkg-config.in
Some build systems (i. e. meson) try to run pkg-config with `--version` argument to check its sanity. This commit makes the wrapper handle this situation (pkg-config does not like `--version` alongside other arguments).
> Handle `--version` for pkg-config

- ppc/libvorbis/PKGBUILD
- switch/libvorbis/PKGBUILD
Unifies the libvorbis version across PPC and Switch, also unifies the download location for the library.
> libvorbis: update to 1.3.7

- switch/libmpeg2/PKGBUILD
Used by ScummVM to enable games like Escape from Monkey Island, which don't work without mpeg2.
PKGBUILD script written by @usineur
> switch: add libmpeg2

- switch/enet/PKGBUILD
The enet source is cloned from https://github.com/lsalzman/enet , specifically this commit https://github.com/lsalzman/enet/commit/e2ef83927d1626d6ee479742343a3011333fdfdd since there last released version (1.3.13) is more than 3 years old and contains several include issues that prevent it from building for the switch.
> Add enet for the switch

- 3ds/libtheora/PKGBUILD
- 3ds/libtheora/libtheora-1.2.0.patch
The original patch tried to claim that neon was available on the 3ds when it actually isn't. The only reason that this didn't cause a crash was due to sheer incompetence on my part.
> 3ds-libtheora: fix armcpu patch

- 3ds/libmodplug/PKGBUILD
- 3ds/libmodplug/libmodplug-0.8.9.0.patch
This pull request aims to add libmodplug to the 3ds packages. Tested locally on my own 3DS. Audio plays as expected.
[3ds-libmodplug-example.zip](https://github.com/devkitPro/pacman-packages/files/6611872/3ds-libmodplug-example.zip)
https://streamable.com/38pnl3
> add 3ds-libmodplug

- 3ds/wslay/PKGBUILD
Here is a working example program, adapted from wslay's examples, with the 3ds connecting to a websocat server: [wslay-client.zip](https://github.com/devkitPro/pacman-packages/files/6673296/wslay-client.zip)
`gcc` is in nettle's `makedepends` because it seems nettle needs to build utilities to run on the build system at build time.
Please feel free to make any changes.
> 3ds: add wslay and nettle

- switch/libmad/PKGBUILD
devkitA64 provides a libmad compiled without the -fPIC flag.
It means that linking fails with error "read-only segment has dynamic relocations".
This is due to configure script which filters out -fPIC flag because it handles it itself.
To fix this, configure must be run with --with-pic=yes option.
> switch-libmad: force PIC compilation

- switch/libtheora/PKGBUILD
This pull request upgrades switch-libtheora to 1.2.0alpha1. It puts it in line with the 3ds version. It builds and works on-console. Originally I was using switch-libtheora1.1, but this was crashing on `th_decode_packetin`. This actually fixes that. Although I cannot be sure that maybe the old 1.1 package was built incorrectly, for example.
> switch-libtheora: upgrade to 1.2.0alpha1

- cmake/wiiu/CafeOS.cmake
- cmake/wiiu/PKGBUILD
I'm not that much familiar with cmake, so if this PR is not accurate, simply close it 😁
There are a few libraries installed with the wiiu-dev package that are getting installed into the _${DEVKITPRO}/portlibs/ppc/lib_ folder. So I guess that this folder should also be included with the others WUT_LINKER_FLAGS.
> Add missing library path in CafeOS.cmake

- dkp-toolchain-vars/PKGBUILD
`cubevars.sh` isn't installed along with the other scripts, so this PR fixes that.
> dkp-toolchain-vars: Install cubevars.sh

- switch/libssh2/PKGBUILD
- switch/libssh2/disable-tests.patch
With the 8.2 release of OpenSSH, the `ssh-rsa` pubk signature algorithm was deprecated and needs to be explicitely enabled in the guest configuration. Unfortunately, the mbedtls backend of libssh2, in the 1.9 release, only supported this, which made it unable to connect unless `ssh-rsa` was enabled on the guest.  
[This commit](https://github.com/libssh2/libssh2/commit/5528f3da02eba1de425535481de049b21c48e9eb), included in 1.10, adds ECDSA support.
I had to write a patch to disable tests, which wasn't possible in their current buildsystem.
I also switched the download url to github, since their website seems to have intermittent outages.
> switch: Update libssh2 to 1.10.0

- switch/libmpv/PKGBUILD
> switch-libmpv: bump to 0.36.0 (fix for ffmpeg 6.0 changes)

- switch/xxhash/PKGBUILD
NEON intrinsics are verified to be correctly autodetected during build.
The install step is a bit hacky to avoid building executables and manpages, but hopefully those make targets should be stable in future revisions.
> switch-xxhash: new package

- switch/ntfs-3g/PKGBUILD
- switch/ntfs-3g/ntfs-3g-2022.10.3.patch
Based on the original PKGBUILD script + patch from the libusbhsfs repository, plus some extra modifications based on the PPC portlib.
References:
* https://github.com/devkitPro/docker/pull/28
* https://devkitpro.org/viewtopic.php?p=17868
> switch: add ntfs-3g

- switch/lwext4/PKGBUILD
- switch/lwext4/lwext4-1.0.0.patch
Based on the original PKGBUILD script + patch from the libusbhsfs repository, with some extra modifications (e.g. no subfolder creation).
References:
* https://github.com/devkitPro/docker/pull/28
* https://devkitpro.org/viewtopic.php?p=17868
> switch: add lwext4

- switch/libass/PKGBUILD
With its [0.17.2](https://github.com/libass/libass/releases/tag/0.17.2) release libass added optimized assembly routines for aarch64, greatly improving rendering performance.
> switch-libass: 0.17.2

- switch/ffmpeg/PKGBUILD
- switch/ffmpeg/tls.patch
implemented ffmpeg libnx tls backend, for use it you must call `sslInitialize` manually in `userAppInit`
tested with my mpv demo https://gist.github.com/087af5343fa17f72f87420852e887513
> switch-ffmpeg: add libnx tls backend

- cmake/3ds/arm-none-eabi-cmake
- cmake/devkita64/aarch64-none-elf-cmake
- cmake/devkitarm/arm-none-eabi-cmake
- cmake/devkitppc/powerpc-eabi-cmake
- cmake/gamecube/powerpc-eabi-cmake
- cmake/gba/arm-none-eabi-cmake
- cmake/nds/arm-none-eabi-cmake
- cmake/switch/aarch64-none-elf-cmake
- cmake/wii/powerpc-eabi-cmake
- cmake/wiiu/powerpc-eabi-cmake
The `-D` option can't be used with some CMake subcommands, including `--build` and `--install`. 
Solves CLion not being able to build projects when the toolchain CMake path is set to one of the `<platform>-cmake` scripts.
> Use `CMAKE_TOOLCHAIN_FILE` env var instead of passing as `-D` parameter

- switch/libzstd/PKGBUILD
Files added:
- lib/cmake/zstd/zstdConfig.cmake
- lib/cmake/zstd/zstdConfigVersion.cmake
- lib/cmake/zstd/zstdTargets.cmake
- lib/cmake/zstd/zstdTargets-release.cmake
which allow this to link a project with the `zstd` library:
```
find_package(zstd)
target_link_libraries(${PROJECT_NAME} PRIVATE zstd::libzstd_static)
```
> switch-libzstd: 1.5.7 and use cmake to build

- ppc/libjpeg-turbo/PKGBUILD
Prevents libjpeg-turbo from trying to use altivec
I am not knowledgeable enough to add paired singles support to the lib, but at least this makes it work.
> ppc-libjpeg-turbo: Disable SIMD 
